Rollup changes to main (#456)
* update readme [sairuk]
* update sabretools install [sairuk]
* update documentation links [sairuk]
* update systems list [sairuk]
* preliminary work for debian13 support [sairuk]
* Update README.md - fix typo (#455) [Erich Moraga]
* check for successful ip discovery [sairuk]

diff --git a/ansible/templates/install_hb-store-cdn/install_hb-store-cdn.sh.j2 b/ansible/templates/install_hb-store-cdn/install_hb-store-cdn.sh.j2
--- a/ansible/templates/install_hb-store-cdn/install_hb-store-cdn.sh.j2
+++ b/ansible/templates/install_hb-store-cdn/install_hb-store-cdn.sh.j2
@@ -18,6 +18,10 @@ REPO=https://github.com/Gkiokan/hb-store-cdn-cli-server.git
 
 [ ! -x /usr/bin/npm ] && echo "npm could not be found" && exit 1
 
+# max version we can build with is node18
+npm install -g node@18.20.8
+npm install -g npm@10.8.2                                                          
+
 echo "Configuring build directories..."
 rm -rf "${SRCDIR}"
 mkdir -p "${SRCDIR}"
@@ -28,8 +32,8 @@ git clone $REPO $APPNAME
 cd $APPNAME
 
 echo "Install Dependencies"
-npm install
-npm install pkg -g
+/usr/local/bin/npm install
+/usr/local/bin/npm install pkg -g
 
 echo "Set arch (default x86_64)"
 MACH=$(uname -m)
@@ -43,15 +47,18 @@ case $MACH in
 esac
 
 echo "Building"
-npm run build:$ARCH
+/usr/local/bin/npm run build:$ARCH
+
+BUILT=release/hb-store-cdn-cli-server
+[ ! -f $BUILT ] && echo "Build failed" && exit 1
 
 echo "Moving binary to RetroNAS bin dir..."
 mkdir -p "${BINDIR}" 2>/dev/null
-chmod +x release/hb-store-cdn-cli-server
-mv -vf release/hb-store-cdn-cli-server "${BINDIR}"/
+chmod +x $BUILT
+mv -vf $BUILT "${BINDIR}"/
 
 echo "Cleaning up..."
 rm -rf "${SRCDIR}"
 
-chown -R {{ retronas_user }}:{{ retronas_group }}  "${BINDIR"/
+chown -R {{ retronas_user }}:{{ retronas_group }}  "${BINDIR}"/
 echo "All done!"
diff --git a/ansible/templates/install_sabretools/install_sabretools.sh.j2 b/ansible/templates/install_sabretools/install_sabretools.sh.j2
--- a/ansible/templates/install_sabretools/install_sabretools.sh.j2
+++ b/ansible/templates/install_sabretools/install_sabretools.sh.j2
@@ -1,38 +1,44 @@
 #!/bin/bash
+set -eu
 
-SABREVER=1.1.0
-SABREURL=https://github.com/SabreTools/SabreTools/releases/download/${SABREVER}/SabreTools.v${SABREVER}.x86-64_netcoreapp3.1.zip
-SABRELFILE=/tmp/sabre.zip
-SABRELOCAL=/opt/sabretools
-ISNIGHTLY=0
+APP=SabreTools
+ORG=$APP
+REPO=$APP
+DESTDIR=/opt/${APP}
 
-### SABRETOOLS
-# -- Download
-[ ! -f ${SABRELFILE} ] && wget -qO ${SABRELFILE} ${SABREURL}
-[ $? -ne 0 ] && echo "Sadness getting Sabretools" && exit 1
 
-[ ! -d ${SABRELOCAL} ] && /bin/mkdir ${SABRELOCAL} || echo "Missing ${SABRELOCAL}"
-# -- Unpack
-if [ $ISNIGHTLY == 1 ]
-then
-  [ -f ${SABRELFILE} ] && /usr/bin/unzip -o ${SABRELFILE} -d /tmp/ || echo "Missing: ${SABRELFILE}"
-  mv /tmp/SabreTools/bin/Debug/netcoreapp3.1/* ${SABRELOCAL}/
-else
-  [ -f ${SABRELFILE} ] && /usr/bin/unzip -o ${SABRELFILE} -d ${SABRELOCAL} || echo "Missing: ${SABRELFILE}"
-fi
+case $(uname -m) in
+    x86_64)
+        ARCH=x64
+        ;;
 
-# -- create sabretools exec
-cat << 'EOST' > /usr/local/bin/sabretools
-#!/bin/bash
-PATH=/opt/sabretools:{{ retronas_root }}/bin/dotnetcore3:{{ retronas_root }}/bin/dotnetcore3/tools:${PATH}
-DOTNET_ROOT={{ retronas_root }}/bin/dotnetcore3
-export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
-dotnet /opt/sabretools/SabreTools.dll $*
-EOST
+    aarch64)
+        ARCH=arm64
+        ;;
+    *)
+      echo "Unsupported arch"
+      exit 1
+esac
 
-# -- Perms
-chmod +x /usr/local/bin/sabretools
-chmod 755 ${SABRELOCAL}
+dl_install() {
+    RELEASE=${1}
+    
+    [ -z "$RELEASE" ] && echo "Couldn't get release " && exit 1
+    [ "$RELEASE" == "null" ] && echo "Couldn't get release " && exit 1
+    [ ! -d "${DESTDIR}" ] && mkdir -p "${DESTDIR}"
 
-### CLEANUP
-rm ${SABRELFILE}
+    RTMP=$(mktemp -d)
+    cd $RTMP
+    curl -sOJL "${RELEASE}"
+
+    FILENAME=$(basename ${RELEASE})
+    if unzip -o $FILENAME -d $DESTDIR
+    then
+      [ -f /usr/local/bin/sabretools ] && rm -f /usr/local/bin/sabretools
+      ln -s ${DESTDIR}/${APP} /usr/local/bin/sabretools
+      rm -rf $RTMP
+    fi
+}
+
+RELEASE=$(curl -skJL https://api.github.com/repos/${ORG}/${REPO}/releases | jq -r ".[0].assets | map(select(.name | match (\"linux-${ARCH}_release\")))[-1] | .browser_download_url" )
+dl_install $RELEASE
